### PR TITLE
Call subscribe() in NetworkObjectReceiver so that pub/sub works

### PR DESCRIPTION
**Pull request by philiprodrigues**
When the IPM Receiver plugin is of "Subscriber" type, we have to add a subscription on the receiving end, otherwise no messages are received. This PR adds that.

### CODE REVIEW

**Comment by eflumerf** [comment]
Does the test config actually set the subscription, or is it testing that simply substituting a ZmqSubscriber for a ZmqReceiver doesn't break the system?

I see a couple possible improvements (which could be made in future PRs): There's no support for setting a publish topic for the QueueToNetwork side, and there may also be a desire for a Subscriber to subscribe to multiple topics.

**Comment by philiprodrigues** [comment]
> Does the test config actually set the subscription, or is it testing that simply substituting a ZmqSubscriber for a ZmqReceiver doesn't break the system?

The subscription was getting implicitly set to "" (subscribe to everything) because that was the default in the schema file. It's better to be explicit, so I've done that in the latest commits
 
> I see a couple possible improvements (which could be made in future PRs): There's no support for setting a publish topic for the QueueToNetwork side, and there may also be a desire for a Subscriber to subscribe to multiple topics.

I like these suggestions, so I've implemented them in today's commits. I made the default subscription again be to everything - this is the opposite of the zmq convention (which is to subscribe to nothing by default), but I think it's less likely to lead to confusion in future. But I'm open to arguments about changing that.

I checked the following cases:

1. No subscription set, so default to subscribing to everything. Consumer sees messages, as it should
2. Subscription set correctly (matches producer). Consumer sees messages, as it should
3. Subscription set _incorrectly_ (does not match producer). Consumer sees _no_ messages, which is desired behaviour

**Comment by philiprodrigues** [comment]
Hm, the unit tests revealed a problem with my implementation which I don't know how to solve. You can only call `subscribe` on a zeromq "SUB" socket - calling it on other types throws an exception. I tried to detect this with a `dynamic_cast` to `ipm::Subscriber`:

https://github.com/DUNE-DAQ/nwqueueadapters/blob/a4997a32c3cb9dde290a6953ddd56f10a89fd47f/include/nwqueueadapters/NetworkObjectReceiver.hpp#L51

But the actual object is a `ZmqReceiverImpl`, which derives from `ipm::Subscriber` (and thence from `ipm::Receiver`) regardless of the underlying socket type. So the cast succeeds even when the socket is not really a subscriber, and then `subscribe()` throws.

I think maybe this needs a change in `ipm`? Make a `Receiver` queryable for whether it supports subscribe, or use some trickery to make the `dynamic_cast<Subscriber>()` fail for `ZmqReceiverImpl`s that are not actually subscribers??

**Comment by eflumerf** [comment]
It might be a bit of a hacky way of doing it, but what about
```CXX
if( conf.ipm_plugin_type.find("Subscriber") != std::string::npos )
```

**Comment by philiprodrigues** [comment]
That sounds reasonable for the moment. I've done that and opened https://github.com/DUNE-DAQ/ipm/issues/48 to remind us to find a more elegant fix

**Review by eflumerf — APPROVED** [review]
I ran the fake_data config several times, checking consumers subscribed to the publisher's topic, subscribed to a different topic, subscribed to a different and the publishers topics, subscribed to the universal topic, and subscribed to no topic at all.

The results were as expected, that the consumer only received data when it was either subscribed to the universal topic or to the topic of the publisher. Additional subscription topics did not affect reception from the publisher's topic.

**Pull request merged**
